# Generated by Django 6.0.6 on 2026-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_app', '0007_alter_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_blocks',
            field=models.ManyToManyField(blank=True, related_name='guest_bookings', to='safari_app.habitatzone'),
        ),
    ]
